version: '3.5'
networks:
  kafka-network:
    name: local-network
    
volumes:
  kafka:

services:

  # kafka broker service
  kafka-broker-bootstrap:
    image: bitnami/kafka:2.3.1
    hostname: kafka-broker
    restart: unless-stopped
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka:/bitnami/kafka
      - ./kafka.properties:/opt/bitnami/kafka/conf/server.properties
      - ./:/app
    working_dir: /app
    networks:
      - local-network


  # zookeeper service
  zookeeper:
    image: bitnami/zookeeper:3.6.2
    hostname: zookeeper
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - local-network


  # kafka administration UI service
  kafkaui:
    image: obsidiandynamics/kafdrop:3.27.0
    hostname: kafkaui
    container_name: kafkaui
    restart: unless-stopped
    ports:
      - "9094:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka-broker:9093
    depends_on:
      - kafka-broker-bootstrap
    networks:
      - local-network
